### PR TITLE
added deployment resources support

### PR DESCRIPTION
**Pull request by astelmashenko**
Fixes #

Jetstream dispatcher handles messages delivery for NatsJetStreamChannel kind, for broker nad channel scenarios. Jetstream controller programmatically creates dispatcher deployment and it has it's drawbacks. One of them is limited control over deployment configuration, especially when it is created by broker controller, which reads only NatsJetStreamChannel spec part.

## Proposed Changes

- 🎁 Add new feature: support k8s api to manage programmatical deployments of jetstream dispatcher.

**Release Note**

```release-note
support k8s api to manage programmatical deployments of jetstream dispatcher.
```

### CODE REVIEW

**Comment by astelmashenko** [comment]
@pierDipi , @aliok , it is ready for initial review of the idea behind this PR. Is it legal approach at all? Maybe you can advice based on your experience on how this is solved for other channel types. Thank you

**Comment by astelmashenko** [comment]
cc @dan-j

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
