### PR TITLE
Update deps and bump cloudevents/sdk-go/sql to 52b12276cc4a

### PR DESCRIPTION
**Pull request by lionelvillard**
/assign @astelmashenko @dan-j

### CODE REVIEW

**Comment by astelmashenko** [comment]
@lionelvillard , I see you downgraded knative.dev/eventing from `v0.34.1-0.20220928014117-bd37622589a4` to `0.28.4`.
Was it intentionally?

**Comment by lionelvillard** [comment]
@astelmashenko it should be good now.

**Comment by astelmashenko** [comment]
@lionelvillard , I've check and see that e2e tests go down. 
```
--- FAIL: TestBrokerDirect (661.33s)
    --- PASS: TestBrokerDirect//Setup/install_recorder (109.22s)
    --- PASS: TestBrokerDirect//Requirement/recorder_is_addressable (0.00s)
    --- PASS: TestBrokerDirect//Setup/install_test_resources (8.97s)
    --- FAIL: TestBrokerDirect//Assert/[Alpha/MUST]MT_broker_with_natss_goes_ready_goes_ready (300.02s)
    --- FAIL: TestBrokerDirect//Assert/[Alpha/MUST]MT_broker_with_natss_delivers_events_the_recorder_received_all_sent_events_within_the_time (240.00s)
    --- PASS: TestBrokerDirect//Teardown/Log_references (0.04s)
FAIL
FAIL	knative.dev/eventing-natss/test/e2e	661.456s
?   	knative.dev/eventing-natss/test/e2e/cmd/producer	[no test files]
?   	knative.dev/eventing-natss/test/e2e/config/direct	[no test files]
FAIL
Error: Process completed with exit code 1.
```

**Comment by astelmashenko** [comment]
@lionelvillard , it seems like this PR is not relevant anymore, see #411

**Pull request closed without merging**
