### PR TITLE
fixed case when no deliver configuration in subscription

### PR DESCRIPTION
**Pull request by astelmashenko**
Fixes bug when subscription does not have delivery dispatcher goes into crashloop

### CODE REVIEW

**Comment by astelmashenko** [comment]
@Cali0707 , I need help with this PR, in some reason codecov calculates coverage deffirently, if I revert my changes and add additional tests it says there is less coverate anyway.
Coverage according to test if I run it locally is 85.1% on codecov I see 79.78% 
Could you please help review and merge this PR, it fixes real issue started as discussion in slack.

**Review by Cali0707 — COMMENTED** [review]
/lgtm

@astelmashenko I don't have the ability to override the codecov checks on release-1.10. If that is needed I think we probably need @pierDipi

**Comment by astelmashenko** [comment]
@pierDipi , there is something with tests coverage, it is not the same if I run tests locally, it lost 6% coverage and I can not merge this PR. Could you please help skip the check?

**Pull request merged**
