### PR TITLE
implemented update subscription

### PR DESCRIPTION
**Pull request by astelmashenko**
Fixes #

Updates subscription configuration on dispatcher: retryConfig, url, reply, deadLetter

- 🐛 Fix bug

**Release Note**

```release-note
Fixes updating of existing subscriptions on dispatcher: retryConfig, url, reply, deadLetter
```

### CODE REVIEW

**Comment by astelmashenko** [comment]
cc @dan-j

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
