### PR TITLE
backported pkg files from release-1.10

### LINKED ISSUE #489: Apply high CPU issues resolved on 1.10 to main
Apply the fixes made in https://github.com/knative-extensions/eventing-natss/pull/426 to `main` since this was only applied on the release-1.10 branch

### PR DESCRIPTION
**Pull request by astelmashenko**
Fixes #489

### CODE REVIEW

**Comment by dan-j** [comment]
/lgtm
/approve

There is a small bug in both versions, but not going to stop merging this.. created a new issue #541 to track that

**Comment by dan-j** [comment]
@astelmashenko Looks like one of the checks are failing on codecov: https://github.com/knative-extensions/eventing-natss/pull/496/checks?check_run_id=23785523290

**Comment by astelmashenko** [comment]
> @astelmashenko Looks like one of the checks are failing on codecov: https://github.com/knative-extensions/eventing-natss/pull/496/checks?check_run_id=23785523290

Yeah, I'll take a look at it.

**Comment by astelmashenko** [comment]
Please check https://github.com/knative-extensions/eventing-natss/pull/545

**Pull request closed without merging**
